### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tythos** [ThatGravyBoat/Duckling#43] opened 2024-12-08 23:18 UTC
### Bug Description

Mod fails on startup w/ 1.21.4; `NullPointerException` on HolidayFruitCakeBlock instantiation.

### How to Reproduce?

```sh
curl https://meta.fabricmc.net/v2/versions/loader/1.21.4/0.16.9/1.0.1/server/jar -o fabric-server-mc.1.21.4-loader.0.16.9-launcher.1.0.1.jar
curl https://mediafilez.forgecdn.net/files/5966/280/fabric-api-0.111.0%2B1.21.4.jar -o mods/fabric-api-0.111.0+1.21.4.jar
curl https://mediafilez.forgecdn.net/files/5876/845/geckolib-fabric-1.21.3-4.7.1.jar -o mods/geckolib-fabric-1.21.3-4.7.1.jar
curl https://mediafilez.forgecdn.net/files/5512/147/duckling-fabric-1.21-5.0.1.jar -o mods/duckling-fabric-1.21-5.0.1.jar
java -Xmx2G -jar fabric-server-mc.1.21.4-loader.0.16.9-launcher.1.0.1.jar nogui
```

### Expected Behavior

Expect 1.21 launch and load via Fabric

### Version

5.0.1

### Mod Loader Version

0.16.9

### Mod Loader

Fabric

### Logs or additional context

Java environment:

```sh
# java -version
openjdk version "21.0.5" 2024-10-15
OpenJDK Runtime Environment (build 21.0.5+11-Ubuntu-1ubuntu122.04)
OpenJDK 64-Bit Server VM (build 21.0.5+11-Ubuntu-1ubuntu122.04, mixed mode, sharing)
```

Loadtime exception:

```sh
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'duckling' at 'tech.thatgravyboat.duckling.fabric.DucklingFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:113) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.4-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.ExceptionInInitializerError
        at knot/tech.thatgravyboat.duckling.Duckling.init(Duckling.java:26) ~[duckling-fabric-1.21-5.0.1.jar:?]
        at knot/tech.thatgravyboat.duckling.fabric.DucklingFabric.onInitialize(DucklingFabric.java:23) ~[duckling-fabric-1.21-5.0.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
Caused by: java.lang.NullPointerException: Block id not set
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at knot/net.minecraft.class_4970$class_2251.method_63505(class_4970.java:669) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_4970.<init>(class_4970.java:110) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2248.<init>(class_2248.java:191) ~[server-intermediary.jar:?]
        at knot/tech.thatgravyboat.duckling.common.items.HolidayFruitCakeBlock.<init>(HolidayFruitCakeBlock.java:29) ~[duckling-fabric-1.21-5.0.1.jar:?]
        at knot/tech.thatgravyboat.duckling.common.registry.ModBlocks.lambda$static$0(ModBlocks.java:18) ~[duckling-fabric-1.21-5.0.1.jar:?]
        at knot/com.teamresourceful.resourcefullib.common.registry.fabric.FabricRegistryEntry.of(FabricRegistryEntry.java:20) ~[resourcefullib-3.0.0-a49f061089de3d49.jar:?]
        at knot/com.teamresourceful.resourcefullib.common.registry.fabric.FabricResourcefulRegistry.register(FabricResourcefulRegistry.java:26) ~[resourcefullib-3.0.0-a49f061089de3d49.jar:?]
        at knot/tech.thatgravyboat.duckling.common.registry.ModBlocks.<clinit>(ModBlocks.java:18) ~[duckling-fabric-1.21-5.0.1.jar:?]
        at knot/tech.thatgravyboat.duckling.Duckling.init(Duckling.java:26) ~[duckling-fabric-1.21-5.0.1.jar:?]
        at knot/tech.thatgravyboat.duckling.fabric.DucklingFabric.onInitialize(DucklingFabric.java:23) ~[duckling-fabric-1.21-5.0.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
```

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Tythos** [comment] 2024-12-08 23:19
I'm a decent developer but haven't done much Java (or any Minecraft mods before) so the best I can do on my fork right now is poke around. Nonetheless, happy to help if needed. Will report if I learn anything useful.

**Comment by ThatGravyBoat** [comment] 2024-12-08 23:20
This is not a bug, the version you downloaded isnt for the right mc version. I just havent updated recently.

**Comment by ThatGravyBoat** [comment] 2024-12-08 23:22
Im closing and making a feature request issue instead: https://github.com/ThatGravyBoat/Duckling/issues/44

**Closed as not planned by ThatGravyBoat** 2024-12-08 23:22 UTC
Labels: bug

**Comment by Tythos** [comment] 2024-12-08 23:25
Sounds good. Let me know if I can help. Surprised there are compatibility breakers but this isn't the only place I've seen 1.21.4 in particular cause issues. Thanks for following up so quickly.
